#!/bin/python

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import subprocess

# MPL settings.
mpl.rcParams['mathtext.fontset'] = 'cm'
mpl.rcParams['font.family'] = 'Latin Modern Roman'

# Datafile vars, for pandas
vars = [
    "iteration",
    "time",
    "patch",
    "level",
    "component",
    "i",
    "j",
    "k",
    "x",
    "y",
    "z",
    "u_rhs",
    "rho_rhs",
    "vcoordx",
    "vcoordy",
    "vcoordz"
]

# Files and data
coord_file = "standing_wave/coordinates-vertex_coords.it000000.p0000.tsv"
state_file = "standing_wave/multipatchwavetoy-rhs.it000000.p0000.tsv"

print("Coordinate file:", coord_file)
print("State file:", state_file)

print("Creating temporary plot data file")
p1 = subprocess.Popen(
    [
        "cut",
        "-f12,13,14",
        coord_file
    ],
    stdout=subprocess.PIPE
)

fout = open("temp.ascii", "w")

p2 = subprocess.run(
    [
        "paste",
        state_file,
        "-"
    ],
    stdin=p1.stdout,
    stdout=fout
)

p1.wait()
fout.close()

print("Reading data")
data = pd.read_csv("temp.ascii", delim_whitespace=True,
                   names=vars, comment="#")

# Z slice data
print("Filtering data for the z = 0 slice")

sliced_data = data.loc[
    (data["vcoordz"] == 0.0) &
    (np.abs(data["x"]) <= 1.0) &
    (np.abs(data["y"]) <= 1.0) &
    (np.abs(data["z"]) <= 1.0)
    # & (state_data["patch"] == 1)
]

# Plots
print("Creating plot")

plt.tricontourf(
    sliced_data["vcoordx"],
    sliced_data["vcoordy"],
    sliced_data["rho_rhs"],
    levels=100
)

plt.colorbar()
plt.tight_layout()
plt.show()
